---
title: "Previous Projects"
---

## Previous Projects

This page showcases my completed projects from various courses and endeavors.

### DSAN 5000: Data Science Project

**Description:**
DMV Crime Data Analysis Utilizing R

Basic Overview of Process: this project involves analyzing a real-world dataset to extract meaningful insights and inform decision-making. Using R, we will clean and visualize the data to identify trends and patterns. The analysis will incorporate statistical techniques such as hypothesis testing and probabilistic models to answer specific data science questions. Predictive models will be constructed to provide actionable knowledge, and the ethical implications of the analysis will be considered throughout. The project will culminate in a comprehensive report and presentation, highlighting the analytical process and key findings.
Questions to Investigate:
- Is the arrest rate on Thanksgiving Eve higher than the average rate?
- Geospatial analysis: are certain areas more susceptible to crime?
- Are repeat crimes common?
- Is there a significant difference between juvenile vs. adult arrests in term of number, severity, etc?

**Materials:**
[map][data]

**Project Website:**
[Project Website](https://ehealy.georgetown.domains/Yelp/)
<div class="project-preview">
  <iframe
    src="https://ehealy.georgetown.domains/Yelp/"
    title="Website preview"
    width="100%"
    height="600"
    style="border: 0; border-radius: 12px;"
    loading="lazy"
  ></iframe>
</div>

**Presentation:**
```{=html}
<iframe src="prev_projects/DSAN_5000/Presentation.pdf" width="100%" height="600px"></iframe>
```

---

### DSAN 5100: Final Project

**Description:**
Add a brief description here.

**Materials:**

**Arrest Rates Report:**
```{=html}
<iframe src="prev_projects/DSAN_5100/5100%20Final%20Project%20-%20Arrest%20Rates.pdf" width="100%" height="600px"></iframe>
```

**Final Report:**
```{=html}
<iframe src="prev_projects/DSAN_5100/DSAN_5100_Report.pdf" width="100%" height="600px"></iframe>
```

---

### DSAN 5200: Final Project

**Description:**
Add a brief description here.

**Materials:**

**Project Report:**
```{=html}
<iframe src="prev_projects/DSAN_5200/final_combined.html" width="100%" height="600px"></iframe>
```

---

### DSAN 5300: Final Project

**Description:**
Add a brief description here.

**Materials:**

**Final Report:**
```{=html}
<iframe src="prev_projects/DSAN_5300/Report_Final.pdf" width="100%" height="600px"></iframe>
```

**Poster:**
```{=html}
<iframe src="prev_projects/DSAN_5300/5300_poster.pptx.pdf" width="100%" height="600px"></iframe>
```

---

### DSAN 5400: Presentation

**Description:**
Add a brief description here.

**Materials:**

**Presentation:**
```{=html}
<iframe src="prev_projects/DSAN_5400/DSAN%205400%20Presentation.pptx.pdf" width="100%" height="600px"></iframe>
```

---

### DSAN 5650: Project Website

**Description:**
Add a brief description here.

**Materials:**

**Project Website:**
```{=html}
<iframe src="prev_projects/DSAN_5650/index.html" width="100%" height="600px"></iframe>
```

---

### DSAN 6000: Project Website

**Description:**
Add a brief description here.

**Materials:**

**Project Website:**
```{=html}
<iframe src="prev_projects/DSAN_6000/docs/index.html" width="100%" height="600px"></iframe>
```

---

### DSAN 6300: Project Website

**Description:**
Add a brief description here.

**Materials:**

**Project Website:**

<div class="project-preview">
  <iframe
    src="https://ehealy.georgetown.domains/SQL/"
    title="Website preview"
    width="100%"
    height="600"
    style="border: 0; border-radius: 12px;"
    loading="lazy"
  ></iframe>
</div>

---

### DSAN 6600: Group Project

**Description:**
Add a brief description here.

**Materials:**

**Presentation:**
```{=html}
<iframe src="prev_projects/DSAN_6600/6600_group4_presentation.pdf" width="100%" height="600px"></iframe>
```

**Final Report:**
```{=html}
<iframe src="prev_projects/DSAN_6600/Grp4_Final_Report.pdf" width="100%" height="600px"></iframe>
```

---


### Scholarship: Home Page

**Description:**
Add a brief description here.

**Materials:**

<div class="project-preview">
  <iframe
    src="https://ehealy.georgetown.domains/Scholarship/home.html"
    title="Website preview"
    width="100%"
    height="600"
    style="border: 0; border-radius: 12px;"
    loading="lazy"
  ></iframe>
</div>

---

### Economics 203: Team Project

**Description:**
Add a brief description here.

**Materials:**

```{=html}
<iframe src="prev_projects/Econ_203/TeamCurran_Installment%204.pdf" width="100%" height="600px"></iframe>
```

---

### Economics 304: Final Project

**Description:**
Salaries and Sports: A Look into the Financial Effect of College Athletics

This econometrics papers investigates the financial impact of college athletics on post-graduation salaries. Using a person-year dataset of college students from four institutions between 2012 and 2019, the data includes labor, personal statistics, job salaries, and sports participation information. The research examines the effect of varsity versus club-level sports, as well as gender differences in salary outcomes. Healy employs log-log regression models and incorporates fixed effects to account for individual, time, and sport-specific variations, correcting for heteroscedasticity and autocorrelation. The results indicate a significant negative impact of varsity sports participation on salaries, with varsity athletes earning less than non-athletes on average, while female varsity athletes tend to earn more compared to their male counterparts, although the latter result is less precise. The findings highlight the complexity of measuring the financial returns of college sports and suggest that athletics may not benefit post-college earnings as previously assumed.

**Materials:**
[do file][paper]

```{=html}
<iframe src="prev_projects/Econ_304/Healy-Final%20Project.pdf" width="100%" height="600px"></iframe>
```

---

### Economics 384: Research Project

**Description:**
The Impact of Act 39 on Employment, Hours, and Earnings in the Alcohol Retail Market in Pennsylvania

This project examines how Pennsylvania's Act 39, which removed Sunday restrictions on alcohol sales, influenced labor market outcomes within the state's beer, wine, and liquor retail industry. Using quarterly data from the Pennsylvania Department of Labor's QCEW dataset, this study employs a difference-in-difference approach to assess changes in employment, wages, and hours worked across 67 counties. By comparing the beer, wine, and liquor industry with other non-retail sectors, the analysis aims to isolate the effects of Act 39. The project also explores potential spillover effects in border counties and runs robustness tests, including a placebo test with neighboring states, to validate the findings. Through these methods, the study provides insights into the labor market impacts of deregulation in a state-controlled alcohol market.

**Materials:**
[paper][slides]

**Research Paper:**
```{=html}
<iframe src="prev_projects/Econ_384/Research%20Paper.pdf" width="100%" height="600px"></iframe>
```

**Final Presentation:**
```{=html}
<iframe src="prev_projects/Econ_384/Final%20Presentation.pdf" width="100%" height="600px"></iframe>
```

---

### Economics 396: Senior Undergraduate Thesis

**Description:**
This research examines the influence of directorial quality on both box-office revenue and critical acclaim within the U.S. entertainment industry. Data was collected from multiple public sources, including Kaggle, The Numbers, and IMDb, covering films released from 2002 to 2016. The dataset includes key variables such as domestic gross, production budget, IMDb ratings, director experience, and accumulated awards. Data cleaning involved merging datasets, addressing missing values, and ensuring consistency across fields like production budget and genre classifications.
Methodologically, the analysis applied Ordinary Least Squares (OLS) regression to estimate the effects of directorial quality on film success. Two primary independent variables were constructed: one based on the director’s historical box-office revenue and the other on critical acclaim measured through awards and nominations. The models incorporated controls for film characteristics (e.g., runtime, MPAA rating) and director-specific factors (e.g., previous acting experience, gender). Robustness checks were performed to validate the results, and additional fixed effects were added to account for the film's production budget and previous director-actor collaborations. This approach allowed for a comprehensive analysis of how leadership in film production impacts both financial and critical outcomes.

[thesis paper] [folder of do files] [slideshow]

**Materials:**

```{=html}
<iframe src="prev_projects/Econ_396/Elizabeth%20Healy_Thesis.pdf" width="100%" height="600px"></iframe>
```

---

### Math 210: Optimization Project

**Description:**
Optimization of Bus Routes Utilizing MATLAB

This optimization project works to develop a model for efficiently allocating buses across 20 stops and 8 routes. The project aimed to minimize passenger wait times and bus operation costs by determining the optimal number of buses per route. The model used binary matrices to identify route connections, calculated rider distribution proportions, and optimized the allocation using iterative approaches. The final solution balanced service quality and operational expenses, providing a data-driven strategy for efficient bus routing.

**Materials:**
[m file][paper]

```{=html}
<iframe src="prev_projects/Math_210/Optimization%20Project%20Proposal-2.pdf" width="100%" height="600px"></iframe>
```

---

### Math 210 (Section 2): Final Project

**Description:**
Minimum Spanning Trees: An Investigation of their Applications and Algorithms

This project explores the implementation of Prim's algorithm to find minimum spanning trees (MSTs) from an undirected, edge-weighted graph. The coding aspect involves creating a graph representation with a 2D array and iteratively selecting the minimum weight edges to build an MST. The project also applies these concepts to a real-world example using Haverford College’s campus map, calculating paths between buildings to optimize for minimal total distance while connecting all points. Additionally, the project compares the MST approach with maximum flow solutions, highlighting the efficiency and difference in outcome between these algorithms.
This project explores the implementation of Prim's algorithm to find minimum spanning trees (MSTs) from an undirected, edge-weighted graph. The coding aspect involves creating a graph representation with a 2D array and iteratively selecting the minimum weight edges to build an MST. The project also applies these concepts to a real-world example using Haverford College’s campus map, calculating paths between buildings to optimize for minimal total distance while connecting all points. Additionally, the project compares the MST approach with maximum flow solutions, highlighting the efficiency and difference in outcome between these algorithms.

**Materials:**
[paper][web][map]

```{=html}
<iframe src="prev_projects/Math_210_2/Healy-Final%20Project.pdf" width="100%" height="600px"></iframe>
```

---

### Math 382: Research Project

**Description:**
Cutting the Cheese: Simulating Infectious Disease Spread with Fiction

This paper simulates the spread of infectious diseases using a fictional model inspired by the "cheese touch" game from Diary of a Wimpy Kid. The model is based on a modified Susceptible-Infected-Recovered (SIR) framework, incorporating unique rules from the game, such as passing the infection through touch, a time-limited infection period, and a defense mechanism represented by crossing fingers. Multiple iterations of the model are developed, each with varying assumptions about infection spread, and the simulations are conducted using MATLAB. Key metrics, such as the basic reproduction number (R₀), are calculated to assess the spread dynamics across different iterations.
This paper simulates the spread of infectious diseases using a fictional model inspired by the "cheese touch" game from Diary of a Wimpy Kid. The model is based on a modified Susceptible-Infected-Recovered (SIR) framework, incorporating unique rules from the game, such as passing the infection through touch, a time-limited infection period, and a defense mechanism represented by crossing fingers. Multiple iterations of the model are developed, each with varying assumptions about infection spread, and the simulations are conducted using MATLAB. Key metrics, such as the basic reproduction number (R₀), are calculated to assess the spread dynamics across different iterations

This paper simulates the spread of infectious diseases using a fictional model inspired by the "cheese touch" game from Diary of a Wimpy Kid. The model is based on a modified Susceptible-Infected-Recovered (SIR) framework, incorporating unique rules from the game, such as passing the infection through touch, a time-limited infection period, and a defense mechanism represented by crossing fingers. Multiple iterations of the model are developed, each with varying assumptions about infection spread, and the simulations are conducted using MATLAB. Key metrics, such as the basic reproduction number (R₀), are calculated to assess the spread dynamics across different iterations
This paper simulates the spread of infectious diseases using a fictional model inspired by the "cheese touch" game from Diary of a Wimpy Kid. The model is based on a modified Susceptible-Infected-Recovered (SIR) framework, incorporating unique rules from the game, such as passing the infection through touch, a time-limited infection period, and a defense mechanism represented by crossing fingers. Multiple iterations of the model are developed, each with varying assumptions about infection spread, and the simulations are conducted using MATLAB. Key metrics, such as the basic reproduction number (R₀), are calculated to assess the spread dynamics across different iterations.

**Materials:**
[paper][slideshow][folder of m files and data]

**Final Paper:**
```{=html}
<iframe src="prev_projects/Math_382/Healy-Research%20Project%20Final.pdf" width="100%" height="600px"></iframe>
```

**Final Presentation:**
```{=html}
<iframe src="prev_projects/Math_382/Healy-Final%20Presentation.pdf" width="100%" height="600px"></iframe>
```

---

### Comp Sci 106: 

**Description:**
Interpretation of Wordle

This project recreates the New York Times Wordle game using Java, with a focus on implementing core data structures and efficient algorithms. The main coding components include a Wordle class to manage game logic, handling word selection, guess validation, and providing feedback on guesses using loops and conditionals. A CSVReader class reads from a file of potential words, while arrays are used to store data efficiently. The program uses ANSI color codes to simulate the game's feedback visually in the command line. The Random and Scanner classes manage word selection and user input, respectively.

**Materials:**
[paper][presentation][java and csv folder]
